version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/core"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/example"
    schedule:
      interval: "weekly"
